language: objective-c
osx_image: xcode8.3
# xcode_workspace: "Ciao Game.xcworkspace"
# xcode_scheme: ciao-game
# xcode_sdk: iphonesimulator10.3

branches:
	only:
    - development
    - master

script:
  - xcodebuild -workspace Ciao\ Game.xcworkspace -scheme ciao-game -sdk iphonesimulator10.3